export enum DomainExceptionCode {
  DEFAULT_DOMAIN_EXCEPTION = "DEFAULT_DOMAIN_EXCEPTION",
  PRODUCT_ID_REQUIRED = "PRODUCT_ID_REQUIRED",
  PRICE_REQUIRED = "PRICE_REQUIRED",
  QUANTITY_REQUIRED = "QUANTITY_REQUIRED",
  PRICE_INVALID = "PRICE_INVALID",
  QUANTITY_INVALID = "QUANTITY_INVALID",
  PRODUCT_GUID_INVALID = "PRODUCT_GUID_INVALID"
}
